"""empty message

Revision ID: 11919f3d111e
Revises: 354fc7d9468b
Create Date: 2025-03-06 08:32:51.811579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11919f3d111e'
down_revision = '354fc7d9468b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_no',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_no',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
