"""empty message

Revision ID: 266e847ea7aa
Revises: 851ed9da173a
Create Date: 2025-02-27 12:00:28.553312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266e847ea7aa'
down_revision = '851ed9da173a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
