"""empty message

Revision ID: 354fc7d9468b
Revises: a9854f873f80
Create Date: 2025-03-06 08:27:58.901047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354fc7d9468b'
down_revision = 'a9854f873f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['order_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
