"""updated password

Revision ID: 501ab726f76f
Revises: 6a3aecc3ae71
Create Date: 2025-02-25 23:21:47.693489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501ab726f76f'
down_revision = '6a3aecc3ae71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
