"""empty message

Revision ID: 60f0a7ec0699
Revises: 4b8bd5ef45de
Create Date: 2025-03-02 09:15:55.407514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f0a7ec0699'
down_revision = '4b8bd5ef45de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_no', sa.String(length=8), nullable=False),
    sa.Column('billed_phone', sa.String(length=9), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('invoice_no')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'locations', ['destination_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('destination_id')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('invoices')
    # ### end Alembic commands ###
