"""updated location

Revision ID: 62ab781ed5e2
Revises: 1ff2a56c0690
Create Date: 2025-02-26 08:12:28.079962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ab781ed5e2'
down_revision = '1ff2a56c0690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_location_id_key', type_='unique')
        batch_op.drop_constraint('users_location_id_fkey', type_='foreignkey')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_location_id_fkey', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
        batch_op.create_unique_constraint('users_location_id_key', ['location_id'])

    # ### end Alembic commands ###
