"""empty message

Revision ID: 851ed9da173a
Revises: 990fa3a28a82
Create Date: 2025-02-27 11:47:33.426863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851ed9da173a'
down_revision = '990fa3a28a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('store', sa.UUID(), nullable=False))
        batch_op.drop_constraint('products_store_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('products_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category'], ['name'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'stores', ['store'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('category_id')
        batch_op.drop_column('store_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_category_id_fkey', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('products_store_id_fkey', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('store')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
