"""added location

Revision ID: 87604c6a74fa
Revises: 4fd378fcf0a3
Create Date: 2025-02-26 08:00:45.145803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87604c6a74fa'
down_revision = '4fd378fcf0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.UUID(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_unique_constraint(None, ['location_id'])
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('location_id')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
