"""empty message

Revision ID: ab0b96a1abe3
Revises: 11919f3d111e
Create Date: 2025-03-06 08:37:50.850679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0b96a1abe3'
down_revision = '11919f3d111e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('invoice_no',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('billed_phone',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('billed_phone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.alter_column('invoice_no',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###
