"""empty message

Revision ID: abe499865ba1
Revises: c998a46de96e
Create Date: 2025-02-27 19:41:54.612875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe499865ba1'
down_revision = 'c998a46de96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
            existing_type=sa.String(length=15),  # Change this based on your actual existing type
            type_=sa.Float(),
            existing_nullable=True,
            postgresql_using="price::double precision")  # Explicit cast
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
