"""empty message

Revision ID: acb07615c1d6
Revises: 0a57336d38ac
Create Date: 2025-03-04 08:42:04.199082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb07615c1d6'
down_revision = '0a57336d38ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_total_amount_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_unique_constraint('orders_total_amount_key', ['total_amount'])

    # ### end Alembic commands ###
