"""empty message

Revision ID: cef3ad171ab6
Revises: 3a1a082fce42
Create Date: 2025-02-28 08:41:12.565001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef3ad171ab6'
down_revision = '3a1a082fce42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_constraint('tokens_key_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_unique_constraint('tokens_key_key', ['key'])

    # ### end Alembic commands ###
