"""updated location

Revision ID: d32fdca278ae
Revises: 62ab781ed5e2
Create Date: 2025-02-26 08:22:36.201265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32fdca278ae'
down_revision = '62ab781ed5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_constraint('locations_user_id_key', type_='unique')
        batch_op.drop_constraint('locations_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.UUID(), nullable=True))
        batch_op.create_unique_constraint(None, ['location_id'])
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('location_id')

    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('locations_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_unique_constraint('locations_user_id_key', ['user_id'])

    # ### end Alembic commands ###
