"""empty message

Revision ID: dae31ddeaec4
Revises: 2654be66bd6d
Create Date: 2025-02-27 01:53:20.123317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae31ddeaec4'
down_revision = '2654be66bd6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('store_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint('products_category_id_key', type_='unique')
        batch_op.drop_constraint('products_product_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('products_product_name_key', ['product_name'])
        batch_op.create_unique_constraint('products_category_id_key', ['category_id'])
        batch_op.drop_column('store_id')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
